imx-boot_%.bbappend: Remove the wrong COMPATIBLE_MACHINE overwrriten [YOCIMX-2211]
the wrong setting will cause imx8qm/imx8qxp build meets the build break as followed:
  ERROR: Nothing PROVIDES 'imx-boot'